### ISSUE TITLE
Data profiling text limit

### ISSUE THREAD

**Issue by brandomr** [DARPA-ASKEM/knowledge-middleware#161]
Currently the `SIR` test scenario has this response from MIT for data profiling:

```
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/site-packages/rq/worker.py", line 1428, in perform_job
    rv = job.perform()
  File "/usr/local/lib/python3.10/site-packages/rq/job.py", line 1278, in perform
    self._result = self._execute()
  File "/usr/local/lib/python3.10/site-packages/rq/job.py", line 1315, in _execute
    result = self.func(*self.args, **self.kwargs)
  File "/./worker/operations.py", line 556, in data_card
    raise Exception(f"Failed response from MIT: {resp.status_code}, {resp.text}")
Exception: Failed response from MIT: 400, "Input too long. Please reduce the size of your input."
```

This issue is to ensure that we do not exceed the text limit.

**Comment by Tranway1** [comment]
This token limit issue has been fixed and updated on the MIT public endpoint. Please pull version 1.3.0 if you are running MIT service internally.
```
{
  "mitaskem_commit_sha": "99d82fec64102f669e91a566b23a47c2fc321f2d",
  "mitaskem_image_version": "1.3.0"
}
```
